### PR TITLE
Add get host to kernel terminate event

### PR DESCRIPTION
**Pull request by cedvan**
Need host information to statsd monitoring. 
So add `getHost` to event kernel terminate.

### CODE REVIEW

**Comment by b-viguier** [comment]
:+1: 
Just surprised by french comments in this whole class

**Comment by cedvan** [comment]
@b-viguier :+1:, you want refactoring ?

**Comment by b-viguier** [comment]
@cedvan not required for this PR (and too busy to do this by myself right now), but *next time* :smiley:

**Comment by mojoLyon** [comment]
:metal:

**Comment by Oliboy50** [comment]
:+1:

**Pull request merged**
